# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb1190dc269a761edd31ba2f055c16d3c9f563861463578bbf3fb4cb0969de5f51c5a8759f5eec6f9c98cf2655b41fc68d1c003b6c7a9ca0047ef45a1c01259

test:
  secret_key_base: 7da10d7265c169738286f9660c77524fafe4f69d006f5e4e15678a79b4bc9fe03149e169fb4ef80d4d35e42c2a44db1e1b0defba99ebc6699207f1318d3d0445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
